Repository HerodotusDev/hdp-cairo, pull requests merged in 2024-08, with the labels that each got.

#70 fix: div rem with unsigned integer
  src/hdp_input.json
  src/tasks/aggregate_functions/avg.cairo
  src/tasks/aggregate_functions/slr.cairo
Labels: bug

#71 Fix/multi-flavor-block-headers
  packages/contract_bootloader/dryrun_syscall_memorizer_handler/account_memorizer_handler.py
  packages/contract_bootloader/dryrun_syscall_memorizer_handler/header_memorizer_handler.py
  packages/contract_bootloader/dryrun_syscall_memorizer_handler/storage_memorizer_handler.py
  packages/contract_bootloader/syscall_memorizer_handler/account_memorizer_handler.py
  packages/contract_bootloader/syscall_memorizer_handler/header_memorizer_handler.py
  packages/contract_bootloader/syscall_memorizer_handler/storage_memorizer_handler.py
Labels: bug, enhancement

#72 Self hosted buildkit
  .github/workflows/merge.yml
  .github/workflows/pull-request.yml
Labels: enhancement, CI/CD

#69 private_inputs
  .github/workflows/merge.yml
  .github/workflows/pull-request.yml
  packages/contract_bootloader/dryrun_syscall_memorizer_handler/account_memorizer_handler.py
  packages/contract_bootloader/dryrun_syscall_memorizer_handler/header_memorizer_handler.py
  packages/contract_bootloader/dryrun_syscall_memorizer_handler/storage_memorizer_handler.py
  packages/contract_bootloader/syscall_memorizer_handler/account_memorizer_handler.py
  packages/contract_bootloader/syscall_memorizer_handler/header_memorizer_handler.py
  packages/contract_bootloader/syscall_memorizer_handler/storage_memorizer_handler.py
  src/contract_dry_run.cairo
  src/contracts/dry_run_private_inputs/1-declare.sh
  src/contracts/dry_run_private_inputs/2-deploy.sh
  src/contracts/dry_run_private_inputs/Scarb.toml
  src/contracts/dry_run_private_inputs/src/lib.cairo
  src/hdp.cairo
  src/module.cairo
  src/tasks/aggregate_functions/contract.cairo
  src/tasks/computational.cairo
  tools/py/schema.py
Labels: documentation, enhancement, Cairo1, Contract, Cairo0, CI/CD

#73 fix sympy issue
  .github/workflows/merge.yml
  setup.py
Labels: bug, CI/CD
