Repository HerodotusDev/hdp-cairo, pull requests merged in 2024-06, with the labels that each got.

#35 chore: add cairo-compile & program hash to env dockerfile
  environment.dockerfile
  full_test.dockerfile
Labels: CI/CD

#38 Memorizer key change
  packages/contract_bootloader/execute_entry_point.cairo
  packages/contract_bootloader/execute_syscalls.cairo
  packages/contract_bootloader/syscall_handler.py
  src/contracts/example/src/contract/hdp_context/header_memorizer.cairo
  src/contracts/sierra_compile.sh
  src/datalakes/block_sampled_datalake.cairo
  src/datalakes/datalake.cairo
  src/datalakes/txs_in_block_datalake.cairo
  src/decoders/account_decoder.cairo
  src/decoders/header_decoder.cairo
  src/hdp.cairo
  src/hdp_input.json
  src/memorizer.cairo
  src/tasks/aggregate_functions/slr.cairo
  src/tasks/computational.cairo
  src/types.cairo
  src/verifiers/account_verifier.cairo
  src/verifiers/header_verifier.cairo
  src/verifiers/receipt_verifier.cairo
  src/verifiers/storage_item_verifier.cairo
  src/verifiers/transaction_verifier.cairo
  tests/cairo_programs/computational_task.cairo
  tests/cairo_programs/test_vectors.cairo
Labels: enhancement, Cairo0

#40 dryrun syscall handler & hdp_cairo scarb package
  .gitignore
  Makefile
  Scarb.lock
  Scarb.toml
  cairo/Scarb.toml
  cairo/src/lib.cairo
  cairo/src/memorizer.cairo
  cairo/src/memorizer/header_memorizer.cairo
  compile.sh
  packages/contract_bootloader/dryrun_syscall_handler.py
  snfoundry.toml
  src/contracts/simple_linear_regression/.gitignore
  src/contracts/simple_linear_regression/Scarb.toml
  src/contracts/simple_linear_regression/src/lib.cairo
  tools/make/build.sh
  tools/make/build_cairo1.sh
  tools/make/cairo_format_check.sh
  tools/make/contract_casm_compile.sh
  tools/make/format_cairo_files.sh
Labels: enhancement
