Repository HerodotusDev/hdp-cairo, pull requests merged in 2025-08, with the labels that each got.

#200 #2 - Feat/injected state dry run syscall handler & trie labeling
  crates/dry_hint_processor/src/syscall_handler/injected_state/label.rs
  crates/dry_hint_processor/src/syscall_handler/injected_state/mod.rs
  crates/dry_hint_processor/src/syscall_handler/mod.rs
  crates/syscall_handler/src/memorizer.rs
  examples/injected_state/src/lib.cairo
  hdp_cairo/src/injected_state/state.cairo
  src/contract_bootloader/contract_dry_run.cairo
Labels: enhancement, Cairo1, Rust

#204 #3 - UV python package manager
  .codespellrc
  .dockerignore
  .github/workflows/build-cli.yml
  .github/workflows/mdbook.yaml
  .github/workflows/rust-vm.yaml
  .gitignore
  Dockerfile
  Makefile
  README.md
  crates/dry_run/build.rs
  crates/sound_run/build.rs
  pyproject.toml
  setup.sh
  tests/build.rs
  uv.lock
Labels: documentation, enhancement, CI/CD

#206 #1 - Feat/injected state patricia trie reads
  Cargo.lock
  crates/dry_hint_processor/src/syscall_handler/injected_state/mod.rs
  crates/dry_hint_processor/src/syscall_handler/injected_state/write.rs
  crates/hints/src/lib.rs
  crates/hints/src/vars.rs
  crates/hints/src/verifiers/injected_state/inclusion.rs
  crates/sound_hint_processor/src/syscall_handler/injected_state/label.rs
  crates/sound_hint_processor/src/syscall_handler/injected_state/mod.rs
  crates/sound_hint_processor/src/syscall_handler/injected_state/read.rs
  crates/sound_hint_processor/src/syscall_handler/mod.rs
  crates/state_server/Cargo.toml
  crates/state_server/src/api/proof.rs
  crates/state_server/src/api/read.rs
  crates/state_server/src/api/root_to_id.rs
  crates/state_server/src/api/write.rs
  crates/state_server/src/main.rs
  crates/state_server/src/mpt/db/mod.rs
  crates/state_server/src/mpt/db/trie.rs
  crates/state_server/src/mpt/trie/mod.rs
  crates/types/src/cairo/injected_state/label.rs
  crates/types/src/cairo/injected_state/mod.rs
  crates/types/src/cairo/injected_state/read.rs
  crates/types/src/cairo/injected_state/write.rs
  crates/types/src/cairo/mod.rs
  crates/types/src/keys/injected_state/read.rs
  crates/types/src/proofs/injected_state/mod.rs
  examples/injected_state/proofs.json
  examples/injected_state/src/lib.cairo
  hdp_cairo/src/injected_state/state.cairo
  src/contract_bootloader/execute_syscalls.cairo
  src/hdp.cairo
  src/memorizers/injected_state/memorizer.cairo
  src/verifiers/injected_state/verify.cairo
  src/verifiers/verify.cairo
Labels: enhancement, Cairo0, Rust
