Repository HerodotusDev/hdp-cairo, pull requests merged in 2025-02, with the labels that each got.

#134 Adds debug prints to HDP modules
  Cargo.lock
  Cargo.toml
  crates/dry_hint_processor/src/syscall_handler/mod.rs
  crates/sound_hint_processor/src/syscall_handler/mod.rs
  crates/syscall_handler/Cargo.toml
  crates/syscall_handler/src/call_contract/debug.rs
  crates/syscall_handler/src/call_contract/mod.rs
  crates/syscall_handler/src/lib.rs
  hdp_cairo/src/debug.cairo
  hdp_cairo/src/debug/printer.cairo
  hdp_cairo/src/lib.cairo
  src/contract_bootloader/execute_syscalls.cairo
  tests/src/lib.cairo
  tests/src/lib.rs
  tests/src/utils.cairo
  tests/src/utils/debug.cairo
  tests/src/utils/debug.rs
  tests/src/utils/mod.rs
Labels: enhancement, Cairo1, Rust

#141 Optimize/fetcher (EVM)
  crates/fetcher/src/lib.rs
  crates/fetcher/src/proof_keys/evm.rs
  tests/src/evm.cairo
  tests/src/evm/fetcher_modules.cairo
  tests/src/evm/fetcher_modules.rs
  tests/src/evm/mod.rs
Labels: enhancement, Rust

#149 Starknet Fetcher optimizations
  crates/fetcher/src/lib.rs
  crates/fetcher/src/proof_keys/evm.rs
  crates/fetcher/src/proof_keys/mod.rs
  crates/fetcher/src/proof_keys/starknet.rs
Labels: Rust

#152 feat: Add hashers module with Poseidon, Keccak, and Pedersen hash tests
  Cargo.lock
  tests/Cargo.toml
  tests/src/hashers.cairo
  tests/src/hashers/keccak_modules.cairo
  tests/src/hashers/mod.rs
  tests/src/hashers/pedersen_modules.cairo
  tests/src/hashers/poseidon_modules.cairo
  tests/src/hashers/tests_runner.rs
  tests/src/lib.cairo
  tests/src/lib.rs
Labels: enhancement, Cairo1, Rust

#142 Remove dependency on feeder gateway for dry run
  .github/workflows/rust-vm.yaml
  Cargo.lock
  crates/dry_hint_processor/Cargo.toml
  crates/dry_hint_processor/src/syscall_handler/starknet/header.rs
  crates/fetcher/src/proof_keys/mod.rs
  crates/indexer/Cargo.toml
  crates/indexer/src/lib.rs
  crates/indexer/src/models/accumulators.rs
  crates/indexer/src/models/blocks.rs
  crates/indexer/src/models/mod.rs
  crates/types/src/lib.rs
Labels: enhancement, Rust

#153 Docs fix
  docs/src/getting_started.md
  examples/hdp_input.json
  examples/src/account_activity_checker.cairo
  examples/src/hello_world.cairo
  examples/src/lib.cairo
  examples/src/starkgate.cairo
Labels: documentation

#154 github link icon in docs
  docs/book.toml
Labels: documentation

#155 rm play buttons in docs
  docs/src/debugging.md
  docs/src/getting_started.md
Labels: documentation

#158 macos ci
  .github/workflows/rust-vm.yaml
Labels: CI/CD

#166 improved build cli
  .github/workflows/build-cli.yml
Labels: CI/CD

#168 dotenv
  .cargo/config.example.toml
  .github/workflows/build-cli.yml
  .github/workflows/mdbook.yaml
  .gitignore
  Cargo.lock
  Cargo.toml
  README.md
  Scarb.lock
  Scarb.toml
  crates/cli/Cargo.toml
  crates/cli/src/main.rs
  crates/dry_run/Cargo.toml
  crates/dry_run/src/lib.rs
  crates/dry_run/src/main.rs
  crates/indexer/Cargo.toml
  crates/indexer/src/lib.rs
  crates/server/Cargo.toml
  crates/server/src/main.rs
  crates/sound_run/Cargo.toml
  crates/sound_run/build.rs
  crates/sound_run/src/lib.rs
  crates/sound_run/src/main.rs
  docs/src/getting_started.md
  example.env
  examples/average_balance/Scarb.toml
  examples/average_balance/src/lib.cairo
  examples/compose_hdp_input.sh
  examples/hdp_input.json
  examples/hello_world/Scarb.toml
  examples/hello_world/src/lib.cairo
  examples/src/account_activity_checker.cairo
  examples/src/hello_world.cairo
  examples/src/lib.cairo
  examples/starkgate/Scarb.toml
  examples/starkgate/src/lib.cairo
  install-cli.sh
  setup.sh
  tests/Cargo.toml
  tests/src/evm/account_modules.rs
  tests/src/evm/fetcher_modules.rs
  tests/src/evm/header_modules.rs
  tests/src/evm/receipt_modules.rs
  tests/src/evm/storage_modules.rs
  tests/src/evm/transaction_modules.rs
  tests/src/hashers/tests_runner.rs
  tests/src/starknet/header_modules.rs
  tests/src/starknet/storage_modules.rs
  tests/src/utils/debug.rs
Labels: documentation, enhancement

#169 mmr meta output type chain_id added
  crates/types/src/lib.rs
Labels: enhancement

#171 override builds with envs
  Cargo.lock
  Cargo.toml
  crates/dry_run/build.rs
  crates/server/Cargo.toml
  crates/server/build.rs
  crates/server/src/dry_run.rs
  crates/server/src/error.rs
  crates/server/src/fetch_proofs.rs
  crates/server/src/main.rs
  crates/server/src/sound_run.rs
  crates/server/tests/hdp_input.json
  crates/server/tests/hdp_keys.json
  crates/server/tests/hdp_proofs.json
  crates/sound_run/build.rs
  tests/build.rs
Labels: documentation, enhancement
