Repository HerodotusDev/hdp-cairo, pull requests merged in 2025-01, with the labels that each got.

#123 starknet cairo0 refactor
  .github/workflows/add-to-registry.yml
  .github/workflows/merge.yml
  .github/workflows/pull-request.yml
  .github/workflows/rust-vm.yaml
  README.md
  crates/dry_hint_processor/src/syscall_handler/mod.rs
  crates/dry_hint_processor/src/syscall_handler/starknet/header.rs
  crates/dry_hint_processor/src/syscall_handler/starknet/mod.rs
  crates/dry_hint_processor/src/syscall_handler/starknet/storage.rs
  crates/fetcher/src/main.rs
  crates/fetcher/src/proof_keys.rs
  crates/hints/src/verifiers/evm/account_verifier.rs
  crates/hints/src/verifiers/evm/header_verifier.rs
  crates/hints/src/verifiers/evm/storage_item_verifier.rs
  crates/types/src/cairo/starknet/header.rs
  crates/types/src/cairo/starknet/mod.rs
  crates/types/src/cairo/structs.rs
  crates/types/src/keys/starknet/storage.rs
  crates/types/src/proofs/evm/header.rs
  crates/types/src/proofs/evm/receipt.rs
  crates/types/src/proofs/starknet/header.rs
  crates/types/src/proofs/starknet/mod.rs
  crates/types/src/proofs/starknet/storage.rs
  src/hdp.cairo
  src/verifiers/evm/verify.cairo
  src/verifiers/starknet/header_verifier.cairo
  src/verifiers/starknet/storage_verifier.cairo
  src/verifiers/starknet/verify.cairo
  src/verifiers/verify.cairo
  tests/modules/src/tests/mod.rs
Labels: enhancement, Cairo0

#131 Feat/evm transactions
  crates/dry_hint_processor/src/syscall_handler/evm/mod.rs
  crates/dry_hint_processor/src/syscall_handler/evm/transaction.rs
  crates/fetcher/src/main.rs
  crates/fetcher/src/proof_keys.rs
  crates/hints/src/decoder/evm/mod.rs
  crates/hints/src/decoder/evm/normalize_v.rs
  crates/hints/src/lib.rs
  crates/hints/src/utils/mod.rs
  crates/hints/src/verifiers/evm/transaction_verifier.rs
  crates/sound_hint_processor/src/syscall_handler/evm/mod.rs
  crates/sound_hint_processor/src/syscall_handler/evm/receipt.rs
  crates/sound_hint_processor/src/syscall_handler/evm/transaction.rs
  crates/types/src/cairo/evm/transaction.rs
  crates/types/src/cairo/structs.rs
  crates/types/src/keys/header.rs
  crates/types/src/keys/transaction.rs
  hdp_cairo/src/evm/block_tx.cairo
  src/decoders/evm/transaction_decoder.cairo
  src/utils/rlp.cairo
  src/verifiers/evm/block_tx_verifier.cairo
  tests/modules/src/tests.cairo
  tests/modules/src/tests/mod.rs
  tests/modules/src/tests/receipt_modules.cairo
  tests/modules/src/tests/transaction_modules.cairo
  tests/modules/src/tests/transaction_modules.rs
Labels: enhancement, Cairo0, Rust

#127 5 - better cairo-vm runners
  .env.example
  Cargo.lock
  README.md
  crates/dry_hint_processor/src/syscall_handler/evm/mod.rs
  crates/dry_hint_processor/src/syscall_handler/starknet/mod.rs
  crates/dry_run/Cargo.toml
  crates/dry_run/src/main.rs
  crates/sound_hint_processor/src/syscall_handler/evm/mod.rs
  crates/sound_hint_processor/src/syscall_handler/starknet/mod.rs
  crates/sound_run/Cargo.toml
  crates/sound_run/src/main.rs
  crates/types/Cargo.toml
  crates/types/src/error.rs
  crates/types/src/lib.rs
  src/utils/utils.cairo
Labels: Rust

#136 dockerfile update
  Dockerfile
  environment.dockerfile
Labels: enhancement

#139 Keccak syscall support
  Cargo.lock
  Cargo.toml
  crates/dry_hint_processor/src/syscall_handler/mod.rs
  crates/sound_hint_processor/src/syscall_handler/mod.rs
  crates/syscall_handler/Cargo.toml
  crates/syscall_handler/src/keccak.rs
  crates/syscall_handler/src/lib.rs
  crates/types/src/cairo/new_syscalls.rs
  src/contract_bootloader/execute_syscalls.cairo
Labels: Cairo0, Rust

#137 hdp-server
  .gitignore
  Cargo.lock
  Cargo.toml
  crates/fetcher/src/lib.rs
  crates/fetcher/src/main.rs
  crates/server/Cargo.toml
  crates/server/build.rs
  crates/server/src/dry_run.rs
  crates/server/src/error.rs
  crates/server/src/fetch_proofs.rs
  crates/server/src/main.rs
  crates/server/src/sound_run.rs
  crates/server/tests/hdp_input.json
  crates/server/tests/hdp_keys.json
  crates/server/tests/hdp_proofs.json
Labels: Rust, server
